-- MySQL Script generated by MySQL Workbench
-- Mon Aug 20 22:20:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  `tip_usuario` VARCHAR(45) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentario` (
  `idcomentario` INT(11) NOT NULL AUTO_INCREMENT,
  `texto` TEXT NULL DEFAULT NULL,
  `data` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idcomentario`),
  INDEX `fk_comentario_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_comentario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`montadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`montadora` (
  `idmontadora` INT(11) NOT NULL,
  `montadora` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idmontadora`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelo` (
  `idmodelo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_modelo` VARCHAR(45) NULL DEFAULT NULL,
  `montadora_idmontadora` INT(11) NOT NULL,
  PRIMARY KEY (`idmodelo`),
  INDEX `fk_modelo_montadora1_idx` (`montadora_idmontadora` ASC),
  CONSTRAINT `fk_modelo_montadora1`
    FOREIGN KEY (`montadora_idmontadora`)
    REFERENCES `mydb`.`montadora` (`idmontadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8374
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`modelo_ano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelo_ano` (
  `idveiculo` INT(11) NOT NULL AUTO_INCREMENT,
  `ano` VARCHAR(45) NULL DEFAULT NULL,
  `potencia` VARCHAR(45) NULL DEFAULT NULL,
  `portas` VARCHAR(45) NULL DEFAULT NULL,
  `preco` VARCHAR(45) NULL DEFAULT NULL,
  `altura` VARCHAR(45) NULL DEFAULT NULL,
  `comprimento` VARCHAR(45) NULL DEFAULT NULL,
  `largura` VARCHAR(45) NULL DEFAULT NULL,
  `cambio` VARCHAR(45) NULL DEFAULT NULL,
  `velocidade` VARCHAR(45) NULL DEFAULT NULL,
  `tanque_combustivel` VARCHAR(45) NULL DEFAULT NULL,
  `tip_combustivel` VARCHAR(45) NULL DEFAULT NULL,
  `porta_malas` VARCHAR(45) NULL DEFAULT NULL,
  `tip_direcao` VARCHAR(45) NULL DEFAULT NULL,
  `consumo_urb` VARCHAR(45) NULL DEFAULT NULL,
  `consumo_rod` VARCHAR(45) NULL DEFAULT NULL,
  `marcha` VARCHAR(45) NULL DEFAULT NULL,
  `tip_tracao` VARCHAR(45) NULL DEFAULT NULL,
  `porte` VARCHAR(45) NULL DEFAULT NULL,
  `ocupantes` VARCHAR(45) NULL DEFAULT NULL,
  `tip_freio` VARCHAR(45) NULL DEFAULT NULL,
  `tip_veiculo` VARCHAR(45) NULL DEFAULT NULL,
  `modelo_idmodelo` INT(11) NOT NULL,
  `like` INT(11) NULL DEFAULT NULL,
  `dislike` INT(11) NULL DEFAULT NULL,
  `usuario_idusuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idveiculo`),
  INDEX `fk_veiculo_modelo1_idx` (`modelo_idmodelo` ASC),
  INDEX `fk_veiculo_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_veiculo_modelo1`
    FOREIGN KEY (`modelo_idmodelo`)
    REFERENCES `mydb`.`modelo` (`idmodelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_has_modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_has_modelo` (
  `usuario_idusuario` INT(11) NOT NULL,
  `modelo_idmodelo` INT(11) NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `modelo_idmodelo`),
  INDEX `fk_usuario_has_modelo_modelo1_idx` (`modelo_idmodelo` ASC),
  INDEX `fk_usuario_has_modelo_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_usuario_has_modelo_modelo1`
    FOREIGN KEY (`modelo_idmodelo`)
    REFERENCES `mydb`.`modelo` (`idmodelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_modelo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
